/!\Ce Fichier contient des informations essentielles au fonctionnement du site/!\ ---
is_install: true
theme: default
Serveur_name: Happy-Cube
logo: logo_default.bmp
bg: web_font.png
host: localhost
desc: Un serveur minecraft exclusif avec DiamondCMS
lien_vote: http://www.google.com/
Serveur_money: token
favicon: favicon_default
text_jouer_menu: Jouer Sur notre serveur minecraft !<br />Pour celà, suivez ces instructions :<br/><ol><li>Cliquez sur ajouter un serveur, choisissez le nom que vous voulez</li><li>Ensuite rentrez l'adresse du serveur dans le champ IP.</li><li>Cliquez sur connectez, vous êtes sur le serveur !</li></ol>
ip_serveur: play.happy-cube.tk
titre_img_1: Titre de l'info 1
img_1: img_default_min1.png
lien_img_1:
titre_img_2: Titre de l'info 2
lien_img_2:
img_2: img_default_min1.png
titre_img_3: Titre de l'info 3
lien_img_3:
img_3: img_default_min1.png
